apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
  -  name: nginx
    image: nginx:latest
    ports:
    -  containerport: 80
  imagePullSecrets:
  - name: yjw-secret
